services:
  broker:
    image: apache/kafka:3.9.1
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    volumes:
      - broker-data:/opt/kafka/data

  mongodb:
    image: mongo:7.0.23
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: frauddb
    networks:
      - kafka-network
    volumes:
      - mongodb_data:/data/db

networks:
  kafka-network:

volumes:
  broker-data:
  mongodb_data: